#!/usr/bin/env python
"""Assemble the S1 workbook from generated public-data tables.

The analysis scripts write tab-separated result tables under
``spatial_escc_workflow/results/tables`` and review summaries under
``spatial_escc_workflow/reviews``. This helper combines those generated tables
into the submitted S1 workbook layout when the generated source tables are
available locally.
"""

from __future__ import annotations

import csv
import sys
from pathlib import Path


def _early_help_if_requested() -> None:
    if any(arg in {"-h", "--help"} for arg in sys.argv[1:]):
        print((__doc__ or "").strip())
        print(
            "\nUsage:\n"
            "  python scripts/assemble_s1_table.py [output.xlsx]\n\n"
            "Run the primary analysis scripts first. If no output path is supplied, "
            "the workbook is written to supporting_information/S1_Table.xlsx."
        )
        raise SystemExit(0)


_early_help_if_requested()

from openpyxl import Workbook  # noqa: E402
from openpyxl.styles import Font, PatternFill  # noqa: E402


ROOT = Path(__file__).resolve().parents[1]
TABLE_ROOT = ROOT / "spatial_escc_workflow" / "results" / "tables"
REVIEW_ROOT = ROOT / "spatial_escc_workflow" / "reviews"
DEFAULT_OUTPUT = ROOT / "supporting_information" / "S1_Table.xlsx"


SHEET_SOURCES: list[tuple[str, str | None, str]] = [
    ("S1_axis_definitions", None, "Pre-specified axis genes and claim boundaries."),
    ("S2_TCGA_immune", "deep_axis_tcga_immune_associations.tsv", "TCGA ESCC immune/stromal marker associations."),
    ("S3_TCGA_pathway", "deep_axis_tcga_pathway_associations.tsv", "TCGA ESCC pathway associations."),
    ("S4_GSE47404_assoc", "deep_axis_geo_gse47404_associations.tsv", "Independent GSE47404 expression replication associations."),
    ("S5_GSE47404_clinical", "deep_axis_geo_gse47404_clinical_associations.tsv", "Limited GSE47404 clinical/pathology associations."),
    ("S6_GSE53625_mapping", "gse53625_probe_sequence_mapping.tsv", "Target-scope GSE53625 probe-sequence mapping."),
    ("S7_GSE53625_validation", "gse53625_rescue_tumor_normal_validation.tsv", "GSE53625 paired tumor-normal validation."),
    ("S8_HRA003627_source", "hra003627_source_table_quantification.tsv", "HRA003627 ROI-level source-table signature quantification."),
    ("S9_HRA008846_DEG", "hra008846_deg_axis_hits.tsv", "HRA008846 differential-expression and perturbation source-table hits."),
    ("S10_HRA008846_cells", "hra008846_cell_abundance_trends.tsv", "HRA008846 cell-abundance source-table trends."),
    ("S11_HRA008846_LR", "hra008846_ligand_receptor_axis_hits.tsv", "HRA008846 ligand-receptor rows and direct JAG1-NOTCH1 flag."),
    ("S12_GDSC2_drugs", "deep_axis_gdsc2_esca_drug_response.tsv", "GDSC2 ESCA target-class context; not prediction."),
    ("S13_quality_checks", "deep_axis_validation_review.tsv", "Quality-check decisions."),
    ("S14_independent_checks", "independent_patient_and_spatial_quant_review.tsv", "Independent reproducibility check summary."),
    ("S16_data_manifest", "deep_axis_geo_download_manifest.tsv", "Data source URLs, versions and file sizes where generated by scripts."),
    ("S17_gene_set_overlap", "gene_set_overlap.tsv", "Axis-to-comparator gene-set overlap assessment."),
    ("S18_overlap_removed_corr", "overlap_removed_correlations.tsv", "Spearman correlations after removing axis-overlapping genes from comparator panels."),
    ("S19_zscore_sensitivity", "zscore_sensitivity_correlations.tsv", "Within-cohort per-gene z-score sensitivity analysis for core correlations."),
    ("S20_GSE53625_probe_scope", "gse53625_probe_sequence_uniqueness.tsv", "GSE53625 accepted-probe array-design sequence uniqueness and target-scope limitation assessment."),
    ("S21_data_manifest_ext", "data_manifest_extended.tsv", "Extended data-source manifest with checksum and processed-output path fields."),
    ("S22_reproducibility_summary", "reproducibility_summary.tsv", "Explicit sensitivity and data-source boundary summary used in the manuscript."),
]


def read_tsv(path: Path) -> list[list[str]]:
    with path.open("r", encoding="utf-8", newline="") as handle:
        return list(csv.reader(handle, delimiter="\t"))


def write_rows(workbook: Workbook, sheet_name: str, rows: list[list[str]], description: str) -> None:
    sheet = workbook.create_sheet(sheet_name)
    if rows:
        for row in rows:
            sheet.append(row)
    else:
        sheet.append(["status", "description"])
        sheet.append(["source_table_not_available", description])
    for cell in sheet[1]:
        cell.font = Font(bold=True, color="FFFFFF")
        cell.fill = PatternFill("solid", fgColor="4F81BD")
    for column in sheet.columns:
        letter = column[0].column_letter
        max_len = max(len(str(cell.value or "")) for cell in column[:100])
        sheet.column_dimensions[letter].width = min(max(max_len + 2, 12), 60)


def main() -> None:
    output = Path(sys.argv[1]) if len(sys.argv) > 1 else DEFAULT_OUTPUT
    output.parent.mkdir(parents=True, exist_ok=True)

    workbook = Workbook()
    readme = workbook.active
    readme.title = "README"
    readme.append(["sheet", "description", "source_status"])
    for cell in readme[1]:
        cell.font = Font(bold=True, color="FFFFFF")
        cell.fill = PatternFill("solid", fgColor="4F81BD")

    for sheet_name, source_name, description in SHEET_SOURCES:
        source_path = None
        rows: list[list[str]] = []
        if source_name:
            candidates = [TABLE_ROOT / source_name, REVIEW_ROOT / source_name]
            source_path = next((candidate for candidate in candidates if candidate.exists()), None)
            if source_path:
                rows = read_tsv(source_path)
        status = "generated_source_found" if rows else "generated_source_not_found_or_not_applicable"
        readme.append([sheet_name, description, status])
        write_rows(workbook, sheet_name, rows, description)

    workbook.save(output)
    print(f"Wrote {output}")


if __name__ == "__main__":
    main()
